<script lang="ts" setup></script>

<template>
  <div>
    <h1 class="text-xl font-bold">{{ $t("techAndTools") }}</h1>
    <div class="mt-2 flex gap-2 flex-wrap print:hidden">
      <UButton
        label="TypeScript"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-logos-typescript-icon"
        class="cursor-default"
      />
      <UButton
        label="VueJS"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-logos-vue"
        class="cursor-default"
      />
      <UButton
        label="Nuxt"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-logos-nuxt-icon"
        class="cursor-default"
      />
      <UButton
        label="React"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-logos-react"
        class="cursor-default"
      />
      <UButton
        label="Pinia"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-logos-pinia"
        class="cursor-default"
      />
      <UButton
        label="Tailwind"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-logos-tailwindcss-icon"
        class="cursor-default"
      />
      <UButton
        label="Firebase"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-logos-firebase"
        class="cursor-default"
      />
      <UButton
        label="ViteJS"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-logos-vitejs"
        class="cursor-default"
      />
      <UButton
        label="HTML5"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-logos-html-5"
        class="cursor-default"
      />
      <UButton
        label="CSS3"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-logos-css-3"
        class="cursor-default"
      />
      <UButton
        label="Git"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-logos-git-icon"
        class="cursor-default"
      />
      <UButton
        label="Agile/Scrum"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-heroicons-user-group"
        class="cursor-default"
      />
      <UButton
        label="Jira"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-ph-list-checks"
        class="cursor-default"
      />
      <UButton
        label="Kanban"
        color="sky"
        size="xs"
        square
        variant="soft"
        icon="i-ph-kanban-duotone"
        class="cursor-default"
      />
    </div>
    <div class="mt-2 hidden print:flex gap-2 flex-wrap">
      <p>TypeScript</p>
      <p>VueJS</p>
      <p>Nuxt</p>
      <p>React</p>
      <p>Pinia</p>
      <p>Tailwind</p>
      <p>Firebase</p>
      <p>ViteJS</p>
      <p>HTML5</p>
      <p>CSS3</p>
      <p>Git</p>
      <p>Agile/Scrum</p>
      <p>Jira</p>
      <p>Kanban</p>
    </div>
  </div>
</template>
