<script lang="ts" setup></script>

<template>
  <div>
    <h1>{{ $t("technologies") }}</h1>
    <div class="mt-2 flex gap-2 flex-wrap">
      <UButton
        label="TypeScript"
        color="sky"
        size="sm"
        square
        variant="soft"
        icon="i-logos-typescript-icon"
      />
      <UButton
        label="VueJS"
        color="sky"
        size="sm"
        square
        variant="soft"
        icon="i-logos-vue"
      />
      <UButton
        label="Nuxt"
        color="sky"
        size="sm"
        square
        variant="soft"
        icon="i-logos-nuxt-icon"
      />
      <UButton
        label="React"
        color="sky"
        size="sm"
        square
        variant="soft"
        icon="i-logos-react"
      />
      <UButton
        label="Tailwind"
        color="sky"
        size="sm"
        square
        variant="soft"
        icon="i-logos-tailwindcss-icon"
      />
      <UButton
        label="Firebase"
        color="sky"
        size="sm"
        square
        variant="soft"
        icon="i-logos-firebase"
      />
      <UButton
        label="ViteJS"
        color="sky"
        size="sm"
        square
        variant="soft"
        icon="i-logos-vitejs"
      />
      <UButton
        label="HTML5"
        color="sky"
        size="sm"
        square
        variant="soft"
        icon="i-logos-html-5"
      />
      <UButton
        label="CSS"
        color="sky"
        size="sm"
        square
        variant="soft"
        icon="i-logos-css-3"
      />
    </div>
  </div>
</template>
